# Generated by Django 4.1.1 on 2022-10-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField()),
                ("body", models.TextField()),
                ("author", models.CharField(max_length=50)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
